name: CI Pipeline (Demo)

on:
  pull_request:
    branches:
      - main
      - develop
      - devops

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: CI Status
        run: echo "CI is working successfully ✔"