name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - develop
      - devops

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint Check
        run: echo "Lint check passed"

      - name: Test Check
        run: echo "Tests passed"